app = "median-discord-bot"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[experimental]
  auto_rollback = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
